Vagrant.configure("2") do |config|
  # Ubuntu 14.04 base
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "systemconfig", type: "shell",
    path: "vagrant/systemconfig.sh", privileged: true
  config.vm.provision "userconfig", type: "shell",
    path: "vagrant/userconfig.sh", privileged: false
end
